server:
  error:
    include-stacktrace: on-param

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/anime?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    usarname: Michelle Santana
    password: localhost123
  jpa:
    hibernate:
      ddl-auto: update
